language: c

# set git clone depth to 1
# otherwise clone is too slow in osx
git:
  depth: 1

cache:
  directories:
    - github-cache
    - pharo-local

matrix:
  include:
    - env: JOB=bootstrap BOOTSTRAP_ARCH=32 PHARO_VERSION=60

addons:
  apt:
    packages:
    - lib32asound2
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386

script:
- bash ./bootstrap/scripts/bootstrap.sh
- ./bootstrap-cache/vm/pharo bootstrap-cache/Pharo.image test --no-xterm --fail-on-failure ".*"