language: c
env:
  global:
  - PHARO_VERSION=60
  matrix:
  - BOOTSTRAP_ARCH=32
  - BOOTSTRAP_ARCH=64

addons:
  apt:
    packages:
    - lib32asound2
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386

install:
 - "wget -O - get.pharo.org/${PHARO_VERSION}+vm | bash"
# - "./scripts/install-packages.sh"

script:
 - "./pharo Pharo.image ./bootstrap/scripts/bootstrap.st ARCH=${BOOTSTRAP_ARCH} --quit"
 - "bash ./bootstrap/scripts/build.sh"
# - "zip -r bootstrap bootstrap.image" # boot-packages"
# - "./scripts/dropbox_upload.sh upload bootstrap.zip bootstrap-`git describe`-${BOOTSTRAP_ARCH}-${BOOTSTRAP_DISTIRBUTION}-${TRAVIS_JOB_NUMBER}.zip"
